---
#- name: enable foreman ansible module repo on control node
#  import_tasks: fam_collections_repo.yml
#  delegate_to: 127.0.0.1
#
#- name: enable foreman ansible module repo on satellite host
#  include_tasks: fam_collections_repo.yml
#
#- name: install required package python apypie
#  command: foreman-maintain packages install -y python2-apypie
#  args:
#    creates: /usr/lib/python2.7/site-packages/apypie
#
#- name: install foreman ansible module on control node
#  yum:
#    name: ansible-collection-theforeman-foreman
#    state: present
#  delegate_to: 127.0.0.1

- name: include satellite content views variables
  include_vars: "../vars/satellite_content_views.yml"
  tags: [always]

- name: include satellite products variables
  include_vars: "../vars/satellite_products.yml"
  tags: [always]

- name: include satellite activation keys
  include_vars: "../defaults/activation_keys.yml"
  tags: [always]

- name: create orgs and locations
  import_tasks: "{{ role_path }}/tasks/taxonomies.yml"
  tags: [katello,org,location,taxonomies]

- name: setup manifest
  import_tasks: "{{ role_path }}/tasks/manifest.yml"
  tags: [katello,manifest]

- name: build list of all products
  set_fact:
    rhel_product: "{{ rhel_product  }} + [ '{{ item }}' ]"
  loop: "{{ satellite_orgs.0.products }}"
  loop_control:
    label: "{{ item }}"
  when: item + '_product' in hostvars[inventory_hostname]
  tags: [katello,repo,cv,ak,sync_plans]

- name: create lifecycle environments
  import_tasks: "{{ role_path }}/tasks/lifecyle_env.yml"
  tags: [katello,lcenv]

- name: setup up Satellite content
  include_tasks: configure_content.yml
  loop: "{{ rhel_product }}"
  loop_control:
    loop_var: product_item
    label: "{{ product_item }}"
  tags: [katello,sync_plans,repo,cv,ak]

- name: create/update domains
  import_tasks: "{{ role_path }}/tasks/provision.yml"
  tags: [provision,domains,subnets,compute]

- name: create satellite role
  import_tasks: configure_role.yml
  tags: [katello,role]
