---
#TODO: this currently on works on adding one pool to the manifest, this should be able to handle
#      multiple pools
- name: delete or create a subscription allocations with subscriptions and download the manifest
  theforeman.foreman.redhat_manifest:
    name: "{{ item.0.manifest }}"
    username: "{{ rhsm_user }}"
    password: "{{ rhsm_password }}"
    pool_id: "{{ item.1.id }}"
    quantity: "{{ item.1.quantity }}"
    path: "{{ manifest_download_path }}/{{ item.0.manifest }}.zip"
    state: "{{ item.0.manifest_state }}"
    pool_state: "{{ item.1.pool_state }}"
    validate_certs: "{{ rhsm_verify_ssl }}"
  with_subelements:
    - "{{ satellite_orgs }}"
    - pool
  loop_control:
    label: "{{ item.0.manifest }}"
  when: not(item.0.use_local_manifest) and item.0.manifest_rhsm
  register: rhsm_manifest
  tags: [katello,manifest]

- name: copy local manifest to satellite
  copy:
    src: "{{ local_manifest_path }}/{{ item.manifest }}.zip"
    dest: "{{ manifest_download_path }}/{{ item.manifest }}.zip"
    mode: 0644
  register: copy_rhsm_manifest
  with_items: "{{ satellite_orgs }}"
  loop_control: 
    label: "{{ item.manifest }}"
  when: 
    - item.use_local_manifest
  tags: [katello,manifest]

- name: attach manifest to Satellite org
  theforeman.foreman.katello_manifest:
    username: "{{ satellite_admin_user }}"
    password: "{{ satellite_user_pass }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    organization: "{{ item.name }}"
    manifest_path: "{{ manifest_download_path }}/{{ item.manifest }}.zip"
    redhat_repository_url: "{{ item.cdn_url | default(omit) }}"
    state: present
  with_items: "{{ satellite_orgs }}"
  loop_control: 
    label: "{{ item.manifest }}"
  when: rhsm_manifest.changed or copy_rhsm_manifest.changed or item.manifest_force_upload
  tags: [katello,manifest]
