---
- name: Create Domains
  foreman_domain:
    username: "{{ satellite_admin_user }}"
    password: "{{ satellite_user_pass }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    name: "{{ item.name }}"
    organizations: "{{ item.orgs | default(omit) }}"
    locations: "{{ item.locations | default(omit) }}"
    dns_proxy: "{{ item.proxy | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    description: "{{ item.desc | default(omit) }}"
  with_items: "{{ domains }}"
  loop_control:
    label: "{{ item.name }}"
  when: domains is defined

- name: creating subnets
  foreman_subnet:
    username: "{{ satellite_admin_user }}"
    password: "{{ satellite_user_pass }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    name: "{{ item.name }}"
    network: "{{ item.network }}"
    network_type: "{{ item.network_type | default(omit) }}"
    mask: "{{ item.mask | default(omit) }}"
    gateway: "{{ item.gateway | default(omit) }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
    to_ip: "{{ item.to_ip | default(omit) }}"
    boot_mode: "{{ item.boot_mode | default(omit) }}"
    dns_primary: "{{ item.dns1 | default(omit) }}"
    dns_secondary: "{{ item.dns2 | default(omit) }}"
    domains: "{{ item.domains | default(omit) }}"
    dhcp_proxy: "{{ item.dhcp_proxy | default(omit) }}"
    tftp_proxy: "{{ item.tftp_proxy | default(omit) }}"
    dns_proxy: "{{ item.dns_proxy | default(omit) }}"
    remote_execution_proxies: "{{ item.remote_exec_proxy | default(omit) }}"
    vlanid: "{{ item.vlanid | default(omit) }}"
    mtu: "{{ item.mtu | default(omit) }}"
    ipam: "{{ item.ipam | default(omit) }}"
    organizations: "{{ item.organizations | default(omit) }}"
    locations: "{{ item.locations | default(omit) }}"
    state: "{{ item.state }}"
  with_items: "{{ subnets }}"
  loop_control:
    label: "{{ item.name }}" 
  when: subnets is defined

- name: create/update compute resource
  foreman_compute_resource:
    username: "{{ satellite_admin_user }}"
    password: "{{ satellite_user_pass }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    name: "{{ item.name }}"
    organizations: "{{ item.orgs | default(omit) }}"
    locations: "{{ item.locations | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    description: "{{ item.desc | default(omit) }}"
    provider: "{{ item.provider | default(omit) }}" 
    provider_params:
      url: "{{ item.provider_url | default(omit) }}"
      user: "{{ item.provider_user | default(omit) }}"
      password: "{{ item.provider_pass | default(omit) }}"
      datacenter: "{{ item.datacenter | default(omit) }}"
      ovirt_quota: "{{ item.ovirt_quota | default(omit) }}"
      use_v4: "{{ item.ovirt_v4_api | default(omit) }}"
      set_console_password: "{{ item.console_pass | default(omit) }}"
      display_type: "{{ item.display_type | default(omit) }}"
  with_items: "{{ compute_resource }}"
  loop_control:
    label: "{{ item.name }}"
  when: compute_resource is defined
