---
- name: taxonomies | create Organizations
  theforeman.foreman.foreman_organization:
    username: "{{ satellite_admin_user }}"
    password: "{{ satellite_user_pass }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ satellite_orgs }}"
  loop_control:
    label: "{{ item.name }}"
  tags: [katello,taxonomies,org]

- name: taxonomies | create locations
  theforeman.foreman.foreman_location:
    username: "{{ satellite_admin_user }}"
    password: "{{ satellite_user_pass }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    name: "{{ item.1.name }}"
    state: "{{ item.1.state }}"
    #organizations: "{{ location_orgs }}"
    organizations:
      - "{{ item.0.name }}"
  with_subelements:
    - "{{ satellite_orgs }}"
    - location
  loop_control:
    label: "{{ item.1.name }}"
  tags: [katello,taxonomies,location]
